### ISSUE TITLE
geneSetVis Bugs

### ISSUE THREAD

**Issue by bbimber** [kolabx/geneSetVis#18]
hi @kolabx , i noticed a couple things when using geneSetViz:

- if you enter just a list of genes into the 'load data' tab, but you have selected the 'genes + fc' toggle, you get a 'disconnected from server' message.  i assume something crashes.  there should be some kind of sanity-checking on the user's data and it should report a warning instead

- i dont recall if this was already fixed, but when there's no mapped genes the MSigDB tab reports 'error: cannot open Rplots.pdf' when you hit 'run'.

- likewise, DAVID reports 'input should be an enrichedResult or gseaResult object...', which i think also indicates there are no hits. this probably needs some kind of error checking further upstream.

**Comment by ok-gitr** [comment]
hi @bbimber, I made some misc updates that corrects for the first and the second. But i am not able to reproduce the third error, yet.
